//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package fsl.ta.toms.roms.dlwebservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Address complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Address">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mark" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="streetNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="streetName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="poBoxNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="poLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="areaCityTown" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parish" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Address", namespace = "http://object.dl.ws.fsl.org", propOrder = {
    "mark",
    "streetNumber",
    "streetName",
    "poBoxNumber",
    "poLocation",
    "areaCityTown",
    "parish"
})
public class Address {

    @XmlElement(required = true, nillable = true)
    protected String mark;
    @XmlElement(required = true, nillable = true)
    protected String streetNumber;
    @XmlElement(required = true, nillable = true)
    protected String streetName;
    @XmlElement(required = true, nillable = true)
    protected String poBoxNumber;
    @XmlElement(required = true, nillable = true)
    protected String poLocation;
    @XmlElement(required = true, nillable = true)
    protected String areaCityTown;
    @XmlElement(required = true, nillable = true)
    protected String parish;

    /**
     * Gets the value of the mark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMark() {
        return mark;
    }

    /**
     * Sets the value of the mark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMark(String value) {
        this.mark = value;
    }

    /**
     * Gets the value of the streetNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetNumber() {
        return streetNumber;
    }

    /**
     * Sets the value of the streetNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetNumber(String value) {
        this.streetNumber = value;
    }

    /**
     * Gets the value of the streetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetName() {
        return streetName;
    }

    /**
     * Sets the value of the streetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetName(String value) {
        this.streetName = value;
    }

    /**
     * Gets the value of the poBoxNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoBoxNumber() {
        return poBoxNumber;
    }

    /**
     * Sets the value of the poBoxNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoBoxNumber(String value) {
        this.poBoxNumber = value;
    }

    /**
     * Gets the value of the poLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoLocation() {
        return poLocation;
    }

    /**
     * Sets the value of the poLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoLocation(String value) {
        this.poLocation = value;
    }

    /**
     * Gets the value of the areaCityTown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAreaCityTown() {
        return areaCityTown;
    }

    /**
     * Sets the value of the areaCityTown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAreaCityTown(String value) {
        this.areaCityTown = value;
    }

    /**
     * Gets the value of the parish property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParish() {
        return parish;
    }

    /**
     * Sets the value of the parish property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParish(String value) {
        this.parish = value;
    }

}
