//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package fsl.ta.toms.roms.dlwebservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import fsl.ta.toms.roms.bo.AddressBO;


/**
 * <p>Java class for DriverLicenceDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DriverLicenceDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="driversLicenceNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="controlNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="issueDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="expiryDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="disqDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="disqTypeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="disqTypeDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dlClassCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dlClassDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vehicleLicencedToDrive" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="trnNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="middleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nationality" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="address" type="{http://object.dl.ws.fsl.org}Address"/>
 *         &lt;element name="placeOfBirth" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateOfBirth" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parishOfBirth" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="collectorateIssued" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="collectorateFirstIssued" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateFirstIssued" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="licenceStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="photograph" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DriverLicenceDetails", namespace = "http://object.dl.ws.fsl.org", propOrder = {
    "driversLicenceNo",
    "controlNo",
    "issueDate",
    "expiryDate",
    "disqDate",
    "disqTypeCode",
    "disqTypeDesc",
    "dlClassCode",
    "dlClassDesc",
    "vehicleLicencedToDrive",
    "trnNo",
    "lastName",
    "firstName",
    "middleName",
    "nationality",
    "address",
    "placeOfBirth",
    "dateOfBirth",
    "parishOfBirth",
    "gender",
    "collectorateIssued",
    "collectorateFirstIssued",
    "dateFirstIssued",
    "licenceStatus",
    "photograph"
})
public class DriverLicenceDetails {

    @XmlElement(required = true, nillable = true)
    protected String driversLicenceNo;
    @XmlElement(required = true, nillable = true)
    protected String controlNo;
    @XmlElement(required = true, nillable = true)
    protected String issueDate;
    @XmlElement(required = true, nillable = true)
    protected String expiryDate;
    @XmlElement(required = true, nillable = true)
    protected String disqDate;
    @XmlElement(required = true, nillable = true)
    protected String disqTypeCode;
    @XmlElement(required = true, nillable = true)
    protected String disqTypeDesc;
    @XmlElement(required = true, nillable = true)
    protected String dlClassCode;
    @XmlElement(required = true, nillable = true)
    protected String dlClassDesc;
    @XmlElement(required = true, nillable = true)
    protected String vehicleLicencedToDrive;
    @XmlElement(required = true, nillable = true)
    protected String trnNo;
    @XmlElement(required = true, nillable = true)
    protected String lastName;
    @XmlElement(required = true, nillable = true)
    protected String firstName;
    @XmlElement(required = true, nillable = true)
    protected String middleName;
    @XmlElement(required = true, nillable = true)
    protected String nationality;
    @XmlElement(required = true, nillable = true)
    protected AddressBO address;
    @XmlElement(required = true, nillable = true)
    protected String placeOfBirth;
    @XmlElement(required = true, nillable = true)
    protected String dateOfBirth;
    @XmlElement(required = true, nillable = true)
    protected String parishOfBirth;
    @XmlElement(required = true, nillable = true)
    protected String gender;
    @XmlElement(required = true, nillable = true)
    protected String collectorateIssued;
    @XmlElement(required = true, nillable = true)
    protected String collectorateFirstIssued;
    @XmlElement(required = true, nillable = true)
    protected String dateFirstIssued;
    @XmlElement(required = true, nillable = true)
    protected String licenceStatus;
    @XmlElement(required = true)
    protected byte[] photograph;

    /**
     * Gets the value of the driversLicenceNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriversLicenceNo() {
        return driversLicenceNo;
    }

    /**
     * Sets the value of the driversLicenceNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriversLicenceNo(String value) {
        this.driversLicenceNo = value;
    }

    /**
     * Gets the value of the controlNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getControlNo() {
        return controlNo;
    }

    /**
     * Sets the value of the controlNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setControlNo(String value) {
        this.controlNo = value;
    }

    /**
     * Gets the value of the issueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueDate() {
        return issueDate;
    }

    /**
     * Sets the value of the issueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueDate(String value) {
        this.issueDate = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpiryDate(String value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the disqDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisqDate() {
        return disqDate;
    }

    /**
     * Sets the value of the disqDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisqDate(String value) {
        this.disqDate = value;
    }

    /**
     * Gets the value of the disqTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisqTypeCode() {
        return disqTypeCode;
    }

    /**
     * Sets the value of the disqTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisqTypeCode(String value) {
        this.disqTypeCode = value;
    }

    /**
     * Gets the value of the disqTypeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisqTypeDesc() {
        return disqTypeDesc;
    }

    /**
     * Sets the value of the disqTypeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisqTypeDesc(String value) {
        this.disqTypeDesc = value;
    }

    /**
     * Gets the value of the dlClassCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlClassCode() {
        return dlClassCode;
    }

    /**
     * Sets the value of the dlClassCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlClassCode(String value) {
        this.dlClassCode = value;
    }

    /**
     * Gets the value of the dlClassDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlClassDesc() {
        return dlClassDesc;
    }

    /**
     * Sets the value of the dlClassDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlClassDesc(String value) {
        this.dlClassDesc = value;
    }

    /**
     * Gets the value of the vehicleLicencedToDrive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleLicencedToDrive() {
        return vehicleLicencedToDrive;
    }

    /**
     * Sets the value of the vehicleLicencedToDrive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleLicencedToDrive(String value) {
        this.vehicleLicencedToDrive = value;
    }

    /**
     * Gets the value of the trnNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrnNo() {
        return trnNo;
    }

    /**
     * Sets the value of the trnNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrnNo(String value) {
        this.trnNo = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the nationality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationality(String value) {
        this.nationality = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public AddressBO getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAddress(AddressBO value) {
        this.address = value;
    }

    /**
     * Gets the value of the placeOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceOfBirth() {
        return placeOfBirth;
    }

    /**
     * Sets the value of the placeOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceOfBirth(String value) {
        this.placeOfBirth = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfBirth(String value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the parishOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParishOfBirth() {
        return parishOfBirth;
    }

    /**
     * Sets the value of the parishOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParishOfBirth(String value) {
        this.parishOfBirth = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the collectorateIssued property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollectorateIssued() {
        return collectorateIssued;
    }

    /**
     * Sets the value of the collectorateIssued property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollectorateIssued(String value) {
        this.collectorateIssued = value;
    }

    /**
     * Gets the value of the collectorateFirstIssued property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollectorateFirstIssued() {
        return collectorateFirstIssued;
    }

    /**
     * Sets the value of the collectorateFirstIssued property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollectorateFirstIssued(String value) {
        this.collectorateFirstIssued = value;
    }

    /**
     * Gets the value of the dateFirstIssued property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateFirstIssued() {
        return dateFirstIssued;
    }

    /**
     * Sets the value of the dateFirstIssued property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateFirstIssued(String value) {
        this.dateFirstIssued = value;
    }

    /**
     * Gets the value of the licenceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenceStatus() {
        return licenceStatus;
    }

    /**
     * Sets the value of the licenceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenceStatus(String value) {
        this.licenceStatus = value;
    }

    /**
     * Gets the value of the photograph property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getPhotograph() {
        return photograph;
    }

    /**
     * Sets the value of the photograph property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setPhotograph(byte[] value) {
        this.photograph = ((byte[]) value);
    }

}
