//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package fsl.ta.toms.roms.dlwebservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "FslDriversLicenceService", targetNamespace = "http://dl.ws.fsl.org", wsdlLocation = "WEB-INF/wsdl/FslDriversLicence.wsdl")
public class FslDriversLicenceService
    extends Service
{

    private final static URL FSLDRIVERSLICENCESERVICE_WSDL_LOCATION;
    private final static WebServiceException FSLDRIVERSLICENCESERVICE_EXCEPTION;
    private final static QName FSLDRIVERSLICENCESERVICE_QNAME = new QName("http://dl.ws.fsl.org", "FslDriversLicenceService");

    static {
            FSLDRIVERSLICENCESERVICE_WSDL_LOCATION = fsl.ta.toms.roms.dlwebservice.FslDriversLicenceService.class.getResource("/WEB-INF/wsdl/FslDriversLicence.wsdl");
        WebServiceException e = null;
        if (FSLDRIVERSLICENCESERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/FslDriversLicence.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        FSLDRIVERSLICENCESERVICE_EXCEPTION = e;
    }

    public FslDriversLicenceService() {
        super(__getWsdlLocation(), FSLDRIVERSLICENCESERVICE_QNAME);
    }

    public FslDriversLicenceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FSLDRIVERSLICENCESERVICE_QNAME, features);
    }

    public FslDriversLicenceService(URL wsdlLocation) {
        super(wsdlLocation, FSLDRIVERSLICENCESERVICE_QNAME);
    }

    public FslDriversLicenceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FSLDRIVERSLICENCESERVICE_QNAME, features);
    }

    public FslDriversLicenceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FslDriversLicenceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FslDriversLicence
     */
    @WebEndpoint(name = "FslDriversLicence")
    public FslDriversLicence getFslDriversLicence() {
        return super.getPort(new QName("http://dl.ws.fsl.org", "FslDriversLicence"), FslDriversLicence.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FslDriversLicence
     */
    @WebEndpoint(name = "FslDriversLicence")
    public FslDriversLicence getFslDriversLicence(WebServiceFeature... features) {
        return super.getPort(new QName("http://dl.ws.fsl.org", "FslDriversLicence"), FslDriversLicence.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FSLDRIVERSLICENCESERVICE_EXCEPTION!= null) {
            throw FSLDRIVERSLICENCESERVICE_EXCEPTION;
        }
        return FSLDRIVERSLICENCESERVICE_WSDL_LOCATION;
    }

}
