//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package fsl.ta.toms.roms.dlwebservice;

import javax.xml.ws.WebFault;

@WebFault(name = "FslWebServiceException", targetNamespace = "http://exceptions.ws.fsl.org")
public class FslWebServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FslWebServiceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FslWebServiceException_Exception(String message, FslWebServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public FslWebServiceException_Exception(String message, FslWebServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: fsl.ta.toms.roms.dlwebservice.FslWebServiceException
     */
    public FslWebServiceException getFaultInfo() {
        return faultInfo;
    }

}
