//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package fsl.ta.toms.roms.dlwebservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fsl.ta.toms.roms.dlwebservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FslWebServiceException_QNAME = new QName("http://exceptions.ws.fsl.org", "FslWebServiceException");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fsl.ta.toms.roms.dlwebservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetDriversLicenceI }
     * 
     */
    public GetDriversLicenceI createGetDriversLicenceI() {
        return new GetDriversLicenceI();
    }

    /**
     * Create an instance of {@link GetDriversLicenceIResponse }
     * 
     */
    public GetDriversLicenceIResponse createGetDriversLicenceIResponse() {
        return new GetDriversLicenceIResponse();
    }

    /**
     * Create an instance of {@link DriverLicenceDetails }
     * 
     */
    public DriverLicenceDetails createDriverLicenceDetails() {
        return new DriverLicenceDetails();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link FslWebServiceException }
     * 
     */
    public FslWebServiceException createFslWebServiceException() {
        return new FslWebServiceException();
    }

    /**
     * Create an instance of {@link ArrayOf873062395NillableString }
     * 
     */
    public ArrayOf873062395NillableString createArrayOf873062395NillableString() {
        return new ArrayOf873062395NillableString();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FslWebServiceException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://exceptions.ws.fsl.org", name = "FslWebServiceException")
    public JAXBElement<FslWebServiceException> createFslWebServiceException(FslWebServiceException value) {
        return new JAXBElement<FslWebServiceException>(_FslWebServiceException_QNAME, FslWebServiceException.class, null, value);
    }

}
