//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package org.fsl.ws.ticket.object;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrafficTicket complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrafficTicket">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ticketNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="driversLicenceNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="trnNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="issueDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="issueTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="offenceCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="offenceDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fineAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="statusCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="statusDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mandatoryCourtApp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrafficTicket", propOrder = {
    "ticketNo",
    "driversLicenceNo",
    "trnNo",
    "issueDate",
    "issueTime",
    "offenceCode",
    "offenceDesc",
    "fineAmount",
    "statusCode",
    "statusDesc",
    "mandatoryCourtApp"
})
public class TrafficTicket
    implements Serializable
{

    @XmlElement(required = true, nillable = true)
    protected String ticketNo;
    @XmlElement(required = true, nillable = true)
    protected String driversLicenceNo;
    @XmlElement(required = true, nillable = true)
    protected String trnNo;
    @XmlElement(required = true, nillable = true)
    protected String issueDate;
    @XmlElement(required = true, nillable = true)
    protected String issueTime;
    @XmlElement(required = true, nillable = true)
    protected String offenceCode;
    @XmlElement(required = true, nillable = true)
    protected String offenceDesc;
    @XmlElement(required = true, nillable = true)
    protected String fineAmount;
    @XmlElement(required = true, nillable = true)
    protected String statusCode;
    @XmlElement(required = true, nillable = true)
    protected String statusDesc;
    @XmlElement(required = true, nillable = true)
    protected String mandatoryCourtApp;

    /**
     * Gets the value of the ticketNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTicketNo() {
        return ticketNo;
    }

    /**
     * Sets the value of the ticketNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTicketNo(String value) {
        this.ticketNo = value;
    }

    /**
     * Gets the value of the driversLicenceNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriversLicenceNo() {
        return driversLicenceNo;
    }

    /**
     * Sets the value of the driversLicenceNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriversLicenceNo(String value) {
        this.driversLicenceNo = value;
    }

    /**
     * Gets the value of the trnNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrnNo() {
        return trnNo;
    }

    /**
     * Sets the value of the trnNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrnNo(String value) {
        this.trnNo = value;
    }

    /**
     * Gets the value of the issueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueDate() {
        return issueDate;
    }

    /**
     * Sets the value of the issueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueDate(String value) {
        this.issueDate = value;
    }

    /**
     * Gets the value of the issueTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueTime() {
        return issueTime;
    }

    /**
     * Sets the value of the issueTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueTime(String value) {
        this.issueTime = value;
    }

    /**
     * Gets the value of the offenceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOffenceCode() {
        return offenceCode;
    }

    /**
     * Sets the value of the offenceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOffenceCode(String value) {
        this.offenceCode = value;
    }

    /**
     * Gets the value of the offenceDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOffenceDesc() {
        return offenceDesc;
    }

    /**
     * Sets the value of the offenceDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOffenceDesc(String value) {
        this.offenceDesc = value;
    }

    /**
     * Gets the value of the fineAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFineAmount() {
        return fineAmount;
    }

    /**
     * Sets the value of the fineAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFineAmount(String value) {
        this.fineAmount = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusCode(String value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the statusDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusDesc() {
        return statusDesc;
    }

    /**
     * Sets the value of the statusDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusDesc(String value) {
        this.statusDesc = value;
    }

    /**
     * Gets the value of the mandatoryCourtApp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMandatoryCourtApp() {
        return mandatoryCourtApp;
    }

    /**
     * Sets the value of the mandatoryCourtApp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMandatoryCourtApp(String value) {
        this.mandatoryCourtApp = value;
    }

}
