//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:25 AM(foreman)-)
//


package org.fsl.ws.vehicle.object;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VehMvrc complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VehMvrc">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mvrcNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mvrcIssueDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mvrcExpiryDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VehMvrc", propOrder = {
    "mvrcNo",
    "mvrcIssueDate",
    "mvrcExpiryDate"
})
public class VehMvrc
    implements Serializable
{

    @XmlElement(required = true, nillable = true)
    protected String mvrcNo;
    @XmlElement(required = true, nillable = true)
    protected String mvrcIssueDate;
    @XmlElement(required = true, nillable = true)
    protected String mvrcExpiryDate;

    /**
     * Gets the value of the mvrcNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMvrcNo() {
        return mvrcNo;
    }

    /**
     * Sets the value of the mvrcNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMvrcNo(String value) {
        this.mvrcNo = value;
    }

    /**
     * Gets the value of the mvrcIssueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMvrcIssueDate() {
        return mvrcIssueDate;
    }

    /**
     * Sets the value of the mvrcIssueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMvrcIssueDate(String value) {
        this.mvrcIssueDate = value;
    }

    /**
     * Gets the value of the mvrcExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMvrcExpiryDate() {
        return mvrcExpiryDate;
    }

    /**
     * Sets the value of the mvrcExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMvrcExpiryDate(String value) {
        this.mvrcExpiryDate = value;
    }

}
