//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:25 AM(foreman)-)
//


package fsl.ta.toms.roms.ticketwebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "FslTrafficTicket", targetNamespace = "http://ticket.ws.fsl.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FslTrafficTicket {


    /**
     * 
     * @param driversLicenceNo
     * @param fromDate
     * @return
     *     returns fsl.ta.toms.roms.ticketwebservice.ArrayOf206962931687221736NillableTrafficTicket
     * @throws FslWebServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "getTicketsForDriverIReturn", targetNamespace = "")
    @RequestWrapper(localName = "getTicketsForDriverI", targetNamespace = "http://ticket.ws.fsl.org", className = "fsl.ta.toms.roms.ticketwebservice.GetTicketsForDriverI")
    @ResponseWrapper(localName = "getTicketsForDriverIResponse", targetNamespace = "http://ticket.ws.fsl.org", className = "fsl.ta.toms.roms.ticketwebservice.GetTicketsForDriverIResponse")
    public ArrayOf206962931687221736NillableTrafficTicket getTicketsForDriverI(
        @WebParam(name = "driversLicenceNo", targetNamespace = "")
        String driversLicenceNo,
        @WebParam(name = "fromDate", targetNamespace = "")
        String fromDate)
        throws FslWebServiceException_Exception
    ;

    /**
     * 
     * @param driversLicenceNo
     * @param limit
     * @return
     *     returns fsl.ta.toms.roms.ticketwebservice.ArrayOf206962931687221736NillableTrafficTicket
     * @throws FslWebServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "getTicketsForDriverLimitReturn", targetNamespace = "")
    @RequestWrapper(localName = "getTicketsForDriverLimit", targetNamespace = "http://ticket.ws.fsl.org", className = "fsl.ta.toms.roms.ticketwebservice.GetTicketsForDriverLimit")
    @ResponseWrapper(localName = "getTicketsForDriverLimitResponse", targetNamespace = "http://ticket.ws.fsl.org", className = "fsl.ta.toms.roms.ticketwebservice.GetTicketsForDriverLimitResponse")
    public ArrayOf206962931687221736NillableTrafficTicket getTicketsForDriverLimit(
        @WebParam(name = "driversLicenceNo", targetNamespace = "")
        String driversLicenceNo,
        @WebParam(name = "limit", targetNamespace = "")
        int limit)
        throws FslWebServiceException_Exception
    ;

}
