//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:25 AM(foreman)-)
//


package fsl.ta.toms.roms.ticketwebservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "FslTrafficTicketService", targetNamespace = "http://ticket.ws.fsl.org", wsdlLocation = "WEB-INF/wsdl/FslTrafficTicket.wsdl")
public class FslTrafficTicketService
    extends Service
{

    private final static URL FSLTRAFFICTICKETSERVICE_WSDL_LOCATION;
    private final static WebServiceException FSLTRAFFICTICKETSERVICE_EXCEPTION;
    private final static QName FSLTRAFFICTICKETSERVICE_QNAME = new QName("http://ticket.ws.fsl.org", "FslTrafficTicketService");

    static {
            FSLTRAFFICTICKETSERVICE_WSDL_LOCATION = fsl.ta.toms.roms.ticketwebservice.FslTrafficTicketService.class.getResource("/WEB-INF/wsdl/FslTrafficTicket.wsdl");
        WebServiceException e = null;
        if (FSLTRAFFICTICKETSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/FslTrafficTicket.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        FSLTRAFFICTICKETSERVICE_EXCEPTION = e;
    }

    public FslTrafficTicketService() {
        super(__getWsdlLocation(), FSLTRAFFICTICKETSERVICE_QNAME);
    }

    public FslTrafficTicketService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FSLTRAFFICTICKETSERVICE_QNAME, features);
    }

    public FslTrafficTicketService(URL wsdlLocation) {
        super(wsdlLocation, FSLTRAFFICTICKETSERVICE_QNAME);
    }

    public FslTrafficTicketService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FSLTRAFFICTICKETSERVICE_QNAME, features);
    }

    public FslTrafficTicketService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FslTrafficTicketService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FslTrafficTicket
     */
    @WebEndpoint(name = "FslTrafficTicket")
    public FslTrafficTicket getFslTrafficTicket() {
        return super.getPort(new QName("http://ticket.ws.fsl.org", "FslTrafficTicket"), FslTrafficTicket.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FslTrafficTicket
     */
    @WebEndpoint(name = "FslTrafficTicket")
    public FslTrafficTicket getFslTrafficTicket(WebServiceFeature... features) {
        return super.getPort(new QName("http://ticket.ws.fsl.org", "FslTrafficTicket"), FslTrafficTicket.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FSLTRAFFICTICKETSERVICE_EXCEPTION!= null) {
            throw FSLTRAFFICTICKETSERVICE_EXCEPTION;
        }
        return FSLTRAFFICTICKETSERVICE_WSDL_LOCATION;
    }

}
