//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:25 AM(foreman)-)
//


package fsl.ta.toms.roms.ticketwebservice;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="getTicketsForDriverIReturn" type="{http://ticket.ws.fsl.org}ArrayOf_206962931_687221736_nillable_TrafficTicket"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getTicketsForDriverIReturn"
})
@XmlRootElement(name = "getTicketsForDriverIResponse")
public class GetTicketsForDriverIResponse
    implements Serializable
{

    @XmlElement(required = true, nillable = true)
    protected ArrayOf206962931687221736NillableTrafficTicket getTicketsForDriverIReturn;

    /**
     * Gets the value of the getTicketsForDriverIReturn property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOf206962931687221736NillableTrafficTicket }
     *     
     */
    public ArrayOf206962931687221736NillableTrafficTicket getGetTicketsForDriverIReturn() {
        return getTicketsForDriverIReturn;
    }

    /**
     * Sets the value of the getTicketsForDriverIReturn property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOf206962931687221736NillableTrafficTicket }
     *     
     */
    public void setGetTicketsForDriverIReturn(ArrayOf206962931687221736NillableTrafficTicket value) {
        this.getTicketsForDriverIReturn = value;
    }

}
