//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:25 AM(foreman)-)
//


package fsl.ta.toms.roms.ticketwebservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fsl.ta.toms.roms.ticketwebservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FslWebServiceException_QNAME = new QName("http://exceptions.ws.fsl.org", "FslWebServiceException");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fsl.ta.toms.roms.ticketwebservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TrafficTicket }
     * 
     */
    public TrafficTicket createTrafficTicket() {
        return new TrafficTicket();
    }

    /**
     * Create an instance of {@link FslWebServiceException }
     * 
     */
    public FslWebServiceException createFslWebServiceException() {
        return new FslWebServiceException();
    }

    /**
     * Create an instance of {@link ArrayOf8730623951440052060NillableString }
     * 
     */
    public ArrayOf8730623951440052060NillableString createArrayOf8730623951440052060NillableString() {
        return new ArrayOf8730623951440052060NillableString();
    }

    /**
     * Create an instance of {@link GetTicketsForDriverI }
     * 
     */
    public GetTicketsForDriverI createGetTicketsForDriverI() {
        return new GetTicketsForDriverI();
    }

    /**
     * Create an instance of {@link GetTicketsForDriverIResponse }
     * 
     */
    public GetTicketsForDriverIResponse createGetTicketsForDriverIResponse() {
        return new GetTicketsForDriverIResponse();
    }

    /**
     * Create an instance of {@link ArrayOf206962931687221736NillableTrafficTicket }
     * 
     */
    public ArrayOf206962931687221736NillableTrafficTicket createArrayOf206962931687221736NillableTrafficTicket() {
        return new ArrayOf206962931687221736NillableTrafficTicket();
    }

    /**
     * Create an instance of {@link GetTicketsForDriverLimit }
     * 
     */
    public GetTicketsForDriverLimit createGetTicketsForDriverLimit() {
        return new GetTicketsForDriverLimit();
    }

    /**
     * Create an instance of {@link GetTicketsForDriverLimitResponse }
     * 
     */
    public GetTicketsForDriverLimitResponse createGetTicketsForDriverLimitResponse() {
        return new GetTicketsForDriverLimitResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FslWebServiceException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://exceptions.ws.fsl.org", name = "FslWebServiceException")
    public JAXBElement<FslWebServiceException> createFslWebServiceException(FslWebServiceException value) {
        return new JAXBElement<FslWebServiceException>(_FslWebServiceException_QNAME, FslWebServiceException.class, null, value);
    }

}
