//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:25 AM(foreman)-)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ticket.ws.fsl.org")
package fsl.ta.toms.roms.ticketwebservice;
