//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package fsl.ta.toms.roms.trnwebservice;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddressDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddressDTO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mark" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parishCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parishName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="poBoxNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="poLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="streetName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="streetNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="countryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="countryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressDTO", namespace = "http://dto.common.webservices.fsl.org", propOrder = {
    "mark",
    "parishCode",
    "parishName",
    "poBoxNumber",
    "poLocation",
    "streetName",
    "streetNumber",
    "countryCode",
    "countryName"
})
public class AddressDTO
    implements Serializable
{

    @XmlElement(required = true, nillable = true)
    protected String mark;
    @XmlElement(required = true, nillable = true)
    protected String parishCode;
    @XmlElement(required = true, nillable = true)
    protected String parishName;
    @XmlElement(required = true, nillable = true)
    protected String poBoxNumber;
    @XmlElement(required = true, nillable = true)
    protected String poLocation;
    @XmlElement(required = true, nillable = true)
    protected String streetName;
    @XmlElement(required = true, nillable = true)
    protected String streetNumber;
    @XmlElement(required = true, nillable = true)
    protected String countryCode;
    @XmlElement(required = true, nillable = true)
    protected String countryName;

    /**
     * Gets the value of the mark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMark() {
        return mark;
    }

    /**
     * Sets the value of the mark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMark(String value) {
        this.mark = value;
    }

    /**
     * Gets the value of the parishCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParishCode() {
        return parishCode;
    }

    /**
     * Sets the value of the parishCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParishCode(String value) {
        this.parishCode = value;
    }

    /**
     * Gets the value of the parishName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParishName() {
        return parishName;
    }

    /**
     * Sets the value of the parishName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParishName(String value) {
        this.parishName = value;
    }

    /**
     * Gets the value of the poBoxNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoBoxNumber() {
        return poBoxNumber;
    }

    /**
     * Sets the value of the poBoxNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoBoxNumber(String value) {
        this.poBoxNumber = value;
    }

    /**
     * Gets the value of the poLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoLocation() {
        return poLocation;
    }

    /**
     * Sets the value of the poLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoLocation(String value) {
        this.poLocation = value;
    }

    /**
     * Gets the value of the streetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetName() {
        return streetName;
    }

    /**
     * Sets the value of the streetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetName(String value) {
        this.streetName = value;
    }

    /**
     * Gets the value of the streetNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetNumber() {
        return streetNumber;
    }

    /**
     * Sets the value of the streetNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetNumber(String value) {
        this.streetNumber = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the countryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * Sets the value of the countryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryName(String value) {
        this.countryName = value;
    }

}
