//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package fsl.ta.toms.roms.trnwebservice;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BusinessDetailsDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BusinessDetailsDTO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="branches" type="{http://dto.common.webservices.fsl.org}ArrayOfBusinessDTO"/>
 *         &lt;element name="owners" type="{http://dto.common.webservices.fsl.org}ArrayOfOwnerDTO"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusinessDetailsDTO", namespace = "http://dto.common.webservices.fsl.org", propOrder = {
    "branches",
    "owners"
})
public class BusinessDetailsDTO
    implements Serializable
{

    @XmlElement(required = true, nillable = true)
    protected ArrayOfBusinessDTO branches;
    @XmlElement(required = true, nillable = true)
    protected ArrayOfOwnerDTO owners;

    /**
     * Gets the value of the branches property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfBusinessDTO }
     *     
     */
    public ArrayOfBusinessDTO getBranches() {
        return branches;
    }

    /**
     * Sets the value of the branches property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfBusinessDTO }
     *     
     */
    public void setBranches(ArrayOfBusinessDTO value) {
        this.branches = value;
    }

    /**
     * Gets the value of the owners property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfOwnerDTO }
     *     
     */
    public ArrayOfOwnerDTO getOwners() {
        return owners;
    }

    /**
     * Sets the value of the owners property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfOwnerDTO }
     *     
     */
    public void setOwners(ArrayOfOwnerDTO value) {
        this.owners = value;
    }

}
