//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package fsl.ta.toms.roms.trnwebservice;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IndividualDetailsDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IndividualDetailsDTO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="businesses" type="{http://dto.common.webservices.fsl.org}ArrayOfBusinessDTO"/>
 *         &lt;element name="OIndividualDTO" type="{http://dto.common.webservices.fsl.org}IndividualDTO"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IndividualDetailsDTO", namespace = "http://dto.common.webservices.fsl.org", propOrder = {
    "businesses",
    "oIndividualDTO"
})
public class IndividualDetailsDTO
    implements Serializable
{

    @XmlElement(required = true, nillable = true)
    protected ArrayOfBusinessDTO businesses;
    @XmlElement(name = "OIndividualDTO", required = true, nillable = true)
    protected IndividualDTO oIndividualDTO;

    /**
     * Gets the value of the businesses property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfBusinessDTO }
     *     
     */
    public ArrayOfBusinessDTO getBusinesses() {
        return businesses;
    }

    /**
     * Sets the value of the businesses property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfBusinessDTO }
     *     
     */
    public void setBusinesses(ArrayOfBusinessDTO value) {
        this.businesses = value;
    }

    /**
     * Gets the value of the oIndividualDTO property.
     * 
     * @return
     *     possible object is
     *     {@link IndividualDTO }
     *     
     */
    public IndividualDTO getOIndividualDTO() {
        return oIndividualDTO;
    }

    /**
     * Sets the value of the oIndividualDTO property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndividualDTO }
     *     
     */
    public void setOIndividualDTO(IndividualDTO value) {
        this.oIndividualDTO = value;
    }

}
