//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package fsl.ta.toms.roms.trnwebservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fsl.ta.toms.roms.trnwebservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NotValidTrnTypeException_QNAME = new QName("http://exceptions.common.webservices.fsl.org", "NotValidTrnTypeException");
    private final static QName _RetiredTRNException_QNAME = new QName("http://exceptions.common.webservices.fsl.org", "RetiredTRNException");
    private final static QName _InvalidInputException_QNAME = new QName("http://exceptions.common.webservices.fsl.org", "InvalidInputException");
    private final static QName _RequiredInputMissingException_QNAME = new QName("http://exceptions.common.webservices.fsl.org", "RequiredInputMissingException");
    private final static QName _InvalidTRNException_QNAME = new QName("http://exceptions.common.webservices.fsl.org", "InvalidTRNException");
    private final static QName _SystemErrorException_QNAME = new QName("http://exceptions.common.webservices.fsl.org", "SystemErrorException");
    private final static QName _InvalidTrnBranchException_QNAME = new QName("http://exceptions.common.webservices.fsl.org", "InvalidTrnBranchException");
    private final static QName _IncompleteTRNException_QNAME = new QName("http://exceptions.common.webservices.fsl.org", "IncompleteTRNException");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fsl.ta.toms.roms.trnwebservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InvalidInputException }
     * 
     */
    public InvalidInputException createInvalidInputException() {
        return new InvalidInputException();
    }

    /**
     * Create an instance of {@link InvalidTrnBranchException }
     * 
     */
    public InvalidTrnBranchException createInvalidTrnBranchException() {
        return new InvalidTrnBranchException();
    }

    /**
     * Create an instance of {@link RequiredInputMissingException }
     * 
     */
    public RequiredInputMissingException createRequiredInputMissingException() {
        return new RequiredInputMissingException();
    }

    /**
     * Create an instance of {@link IncompleteTRNException }
     * 
     */
    public IncompleteTRNException createIncompleteTRNException() {
        return new IncompleteTRNException();
    }

    /**
     * Create an instance of {@link InvalidTRNException }
     * 
     */
    public InvalidTRNException createInvalidTRNException() {
        return new InvalidTRNException();
    }

    /**
     * Create an instance of {@link RetiredTRNException }
     * 
     */
    public RetiredTRNException createRetiredTRNException() {
        return new RetiredTRNException();
    }

    /**
     * Create an instance of {@link NotValidTrnTypeException }
     * 
     */
    public NotValidTrnTypeException createNotValidTrnTypeException() {
        return new NotValidTrnTypeException();
    }

    /**
     * Create an instance of {@link SystemErrorException }
     * 
     */
    public SystemErrorException createSystemErrorException() {
        return new SystemErrorException();
    }

    /**
     * Create an instance of {@link GetTRNDataResponse }
     * 
     */
    public GetTRNDataResponse createGetTRNDataResponse() {
        return new GetTRNDataResponse();
    }

    /**
     * Create an instance of {@link TrnExtendedDTO }
     * 
     */
    public TrnExtendedDTO createTrnExtendedDTO() {
        return new TrnExtendedDTO();
    }

    /**
     * Create an instance of {@link GetIndividualResponse }
     * 
     */
    public GetIndividualResponse createGetIndividualResponse() {
        return new GetIndividualResponse();
    }

    /**
     * Create an instance of {@link IndividualDTO }
     * 
     */
    public IndividualDTO createIndividualDTO() {
        return new IndividualDTO();
    }

    /**
     * Create an instance of {@link GetFSLService }
     * 
     */
    public GetFSLService createGetFSLService() {
        return new GetFSLService();
    }

    /**
     * Create an instance of {@link GetBusinessDetails }
     * 
     */
    public GetBusinessDetails createGetBusinessDetails() {
        return new GetBusinessDetails();
    }

    /**
     * Create an instance of {@link GetIndividualExtendedResponse }
     * 
     */
    public GetIndividualExtendedResponse createGetIndividualExtendedResponse() {
        return new GetIndividualExtendedResponse();
    }

    /**
     * Create an instance of {@link IndividualExtendedDTO }
     * 
     */
    public IndividualExtendedDTO createIndividualExtendedDTO() {
        return new IndividualExtendedDTO();
    }

    /**
     * Create an instance of {@link GetTRNData }
     * 
     */
    public GetTRNData createGetTRNData() {
        return new GetTRNData();
    }

    /**
     * Create an instance of {@link ValidateProvisionalTrn }
     * 
     */
    public ValidateProvisionalTrn createValidateProvisionalTrn() {
        return new ValidateProvisionalTrn();
    }

    /**
     * Create an instance of {@link GetBusiness }
     * 
     */
    public GetBusiness createGetBusiness() {
        return new GetBusiness();
    }

    /**
     * Create an instance of {@link GetIndividual }
     * 
     */
    public GetIndividual createGetIndividual() {
        return new GetIndividual();
    }

    /**
     * Create an instance of {@link GetIndividualExtended }
     * 
     */
    public GetIndividualExtended createGetIndividualExtended() {
        return new GetIndividualExtended();
    }

    /**
     * Create an instance of {@link GetInvidualDetails }
     * 
     */
    public GetInvidualDetails createGetInvidualDetails() {
        return new GetInvidualDetails();
    }

    /**
     * Create an instance of {@link GetBusinessDetailsResponse }
     * 
     */
    public GetBusinessDetailsResponse createGetBusinessDetailsResponse() {
        return new GetBusinessDetailsResponse();
    }

    /**
     * Create an instance of {@link BusinessDetailsDTO }
     * 
     */
    public BusinessDetailsDTO createBusinessDetailsDTO() {
        return new BusinessDetailsDTO();
    }

    /**
     * Create an instance of {@link ValidateTRN }
     * 
     */
    public ValidateTRN createValidateTRN() {
        return new ValidateTRN();
    }

    /**
     * Create an instance of {@link GetFSLServiceResponse }
     * 
     */
    public GetFSLServiceResponse createGetFSLServiceResponse() {
        return new GetFSLServiceResponse();
    }

    /**
     * Create an instance of {@link ValidateProvisionalTrnResponse }
     * 
     */
    public ValidateProvisionalTrnResponse createValidateProvisionalTrnResponse() {
        return new ValidateProvisionalTrnResponse();
    }

    /**
     * Create an instance of {@link UpdatedTRNList }
     * 
     */
    public UpdatedTRNList createUpdatedTRNList() {
        return new UpdatedTRNList();
    }

    /**
     * Create an instance of {@link GetBusinessResponse }
     * 
     */
    public GetBusinessResponse createGetBusinessResponse() {
        return new GetBusinessResponse();
    }

    /**
     * Create an instance of {@link BusinessDTO }
     * 
     */
    public BusinessDTO createBusinessDTO() {
        return new BusinessDTO();
    }

    /**
     * Create an instance of {@link UpdatedTRNListResponse }
     * 
     */
    public UpdatedTRNListResponse createUpdatedTRNListResponse() {
        return new UpdatedTRNListResponse();
    }

    /**
     * Create an instance of {@link ArrayOf5444426031440052060NillableString }
     * 
     */
    public ArrayOf5444426031440052060NillableString createArrayOf5444426031440052060NillableString() {
        return new ArrayOf5444426031440052060NillableString();
    }

    /**
     * Create an instance of {@link GetInvidualDetailsResponse }
     * 
     */
    public GetInvidualDetailsResponse createGetInvidualDetailsResponse() {
        return new GetInvidualDetailsResponse();
    }

    /**
     * Create an instance of {@link IndividualDetailsDTO }
     * 
     */
    public IndividualDetailsDTO createIndividualDetailsDTO() {
        return new IndividualDetailsDTO();
    }

    /**
     * Create an instance of {@link ValidateTRNResponse }
     * 
     */
    public ValidateTRNResponse createValidateTRNResponse() {
        return new ValidateTRNResponse();
    }

    /**
     * Create an instance of {@link TrnDTO }
     * 
     */
    public TrnDTO createTrnDTO() {
        return new TrnDTO();
    }

    /**
     * Create an instance of {@link OwnerDTO }
     * 
     */
    public OwnerDTO createOwnerDTO() {
        return new OwnerDTO();
    }

    /**
     * Create an instance of {@link ArrayOfOwnerDTO }
     * 
     */
    public ArrayOfOwnerDTO createArrayOfOwnerDTO() {
        return new ArrayOfOwnerDTO();
    }

    /**
     * Create an instance of {@link AddressDTO }
     * 
     */
    public AddressDTO createAddressDTO() {
        return new AddressDTO();
    }

    /**
     * Create an instance of {@link ArrayOfBusinessDTO }
     * 
     */
    public ArrayOfBusinessDTO createArrayOfBusinessDTO() {
        return new ArrayOfBusinessDTO();
    }

    /**
     * Create an instance of {@link EmployerDTO }
     * 
     */
    public EmployerDTO createEmployerDTO() {
        return new EmployerDTO();
    }

    /**
     * Create an instance of {@link TaxpayerNameDTO }
     * 
     */
    public TaxpayerNameDTO createTaxpayerNameDTO() {
        return new TaxpayerNameDTO();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotValidTrnTypeException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://exceptions.common.webservices.fsl.org", name = "NotValidTrnTypeException")
    public JAXBElement<NotValidTrnTypeException> createNotValidTrnTypeException(NotValidTrnTypeException value) {
        return new JAXBElement<NotValidTrnTypeException>(_NotValidTrnTypeException_QNAME, NotValidTrnTypeException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetiredTRNException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://exceptions.common.webservices.fsl.org", name = "RetiredTRNException")
    public JAXBElement<RetiredTRNException> createRetiredTRNException(RetiredTRNException value) {
        return new JAXBElement<RetiredTRNException>(_RetiredTRNException_QNAME, RetiredTRNException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvalidInputException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://exceptions.common.webservices.fsl.org", name = "InvalidInputException")
    public JAXBElement<InvalidInputException> createInvalidInputException(InvalidInputException value) {
        return new JAXBElement<InvalidInputException>(_InvalidInputException_QNAME, InvalidInputException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequiredInputMissingException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://exceptions.common.webservices.fsl.org", name = "RequiredInputMissingException")
    public JAXBElement<RequiredInputMissingException> createRequiredInputMissingException(RequiredInputMissingException value) {
        return new JAXBElement<RequiredInputMissingException>(_RequiredInputMissingException_QNAME, RequiredInputMissingException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvalidTRNException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://exceptions.common.webservices.fsl.org", name = "InvalidTRNException")
    public JAXBElement<InvalidTRNException> createInvalidTRNException(InvalidTRNException value) {
        return new JAXBElement<InvalidTRNException>(_InvalidTRNException_QNAME, InvalidTRNException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SystemErrorException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://exceptions.common.webservices.fsl.org", name = "SystemErrorException")
    public JAXBElement<SystemErrorException> createSystemErrorException(SystemErrorException value) {
        return new JAXBElement<SystemErrorException>(_SystemErrorException_QNAME, SystemErrorException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvalidTrnBranchException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://exceptions.common.webservices.fsl.org", name = "InvalidTrnBranchException")
    public JAXBElement<InvalidTrnBranchException> createInvalidTrnBranchException(InvalidTrnBranchException value) {
        return new JAXBElement<InvalidTrnBranchException>(_InvalidTrnBranchException_QNAME, InvalidTrnBranchException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IncompleteTRNException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://exceptions.common.webservices.fsl.org", name = "IncompleteTRNException")
    public JAXBElement<IncompleteTRNException> createIncompleteTRNException(IncompleteTRNException value) {
        return new JAXBElement<IncompleteTRNException>(_IncompleteTRNException_QNAME, IncompleteTRNException.class, null, value);
    }

}
