//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package fsl.ta.toms.roms.trnwebservice;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrnExtendedDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrnExtendedDTO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="businessInfo" type="{http://dto.common.webservices.fsl.org}BusinessDTO"/>
 *         &lt;element name="individualExtInfo" type="{http://dto.common.webservices.fsl.org}IndividualExtendedDTO"/>
 *         &lt;element name="individualInfo" type="{http://dto.common.webservices.fsl.org}IndividualDTO"/>
 *         &lt;element name="nisRefNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="trnInfo" type="{http://dto.common.webservices.fsl.org}TrnDTO"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrnExtendedDTO", namespace = "http://dto.common.webservices.fsl.org", propOrder = {
    "businessInfo",
    "individualExtInfo",
    "individualInfo",
    "nisRefNumber",
    "trnInfo"
})
public class TrnExtendedDTO
    implements Serializable
{

    @XmlElement(required = true, nillable = true)
    protected BusinessDTO businessInfo;
    @XmlElement(required = true, nillable = true)
    protected IndividualExtendedDTO individualExtInfo;
    @XmlElement(required = true, nillable = true)
    protected IndividualDTO individualInfo;
    @XmlElement(required = true, nillable = true)
    protected String nisRefNumber;
    @XmlElement(required = true, nillable = true)
    protected TrnDTO trnInfo;

    /**
     * Gets the value of the businessInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessDTO }
     *     
     */
    public BusinessDTO getBusinessInfo() {
        return businessInfo;
    }

    /**
     * Sets the value of the businessInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessDTO }
     *     
     */
    public void setBusinessInfo(BusinessDTO value) {
        this.businessInfo = value;
    }

    /**
     * Gets the value of the individualExtInfo property.
     * 
     * @return
     *     possible object is
     *     {@link IndividualExtendedDTO }
     *     
     */
    public IndividualExtendedDTO getIndividualExtInfo() {
        return individualExtInfo;
    }

    /**
     * Sets the value of the individualExtInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndividualExtendedDTO }
     *     
     */
    public void setIndividualExtInfo(IndividualExtendedDTO value) {
        this.individualExtInfo = value;
    }

    /**
     * Gets the value of the individualInfo property.
     * 
     * @return
     *     possible object is
     *     {@link IndividualDTO }
     *     
     */
    public IndividualDTO getIndividualInfo() {
        return individualInfo;
    }

    /**
     * Sets the value of the individualInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndividualDTO }
     *     
     */
    public void setIndividualInfo(IndividualDTO value) {
        this.individualInfo = value;
    }

    /**
     * Gets the value of the nisRefNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNisRefNumber() {
        return nisRefNumber;
    }

    /**
     * Sets the value of the nisRefNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNisRefNumber(String value) {
        this.nisRefNumber = value;
    }

    /**
     * Gets the value of the trnInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TrnDTO }
     *     
     */
    public TrnDTO getTrnInfo() {
        return trnInfo;
    }

    /**
     * Sets the value of the trnInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrnDTO }
     *     
     */
    public void setTrnInfo(TrnDTO value) {
        this.trnInfo = value;
    }

}
