//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package fsl.ta.toms.roms.trnwebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "TrnValidator_SEI", targetNamespace = "http://services.TRNValidator.webservices.fsl.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TrnValidatorSEI {


    /**
     * 
     * @param branchNbr
     * @param trnNbr
     * @return
     *     returns fsl.ta.toms.roms.trnwebservice.BusinessDTO
     * @throws NotValidTrnTypeException_Exception
     * @throws RetiredTRNException_Exception
     * @throws SystemErrorException_Exception
     * @throws InvalidTrnBranchException_Exception
     */
    @WebMethod(action = "getBusiness")
    @WebResult(name = "getBusinessReturn", targetNamespace = "")
    @RequestWrapper(localName = "getBusiness", targetNamespace = "http://services.TRNValidator.webservices.fsl.org", className = "fsl.ta.toms.roms.trnwebservice.GetBusiness")
    @ResponseWrapper(localName = "getBusinessResponse", targetNamespace = "http://services.TRNValidator.webservices.fsl.org", className = "fsl.ta.toms.roms.trnwebservice.GetBusinessResponse")
    public BusinessDTO getBusiness(
        @WebParam(name = "trnNbr", targetNamespace = "")
        Integer trnNbr,
        @WebParam(name = "branchNbr", targetNamespace = "")
        Short branchNbr)
        throws InvalidTrnBranchException_Exception, NotValidTrnTypeException_Exception, RetiredTRNException_Exception, SystemErrorException_Exception
    ;

    /**
     * 
     * @param value
     * @return
     *     returns java.lang.String
     * @throws NotValidTrnTypeException_Exception
     * @throws RetiredTRNException_Exception
     * @throws InvalidTRNException_Exception
     * @throws SystemErrorException_Exception
     * @throws InvalidTrnBranchException_Exception
     * @throws IncompleteTRNException_Exception
     */
    @WebMethod(action = "getFSLService")
    @WebResult(name = "getFSLServiceReturn", targetNamespace = "")
    @RequestWrapper(localName = "getFSLService", targetNamespace = "http://services.TRNValidator.webservices.fsl.org", className = "fsl.ta.toms.roms.trnwebservice.GetFSLService")
    @ResponseWrapper(localName = "getFSLServiceResponse", targetNamespace = "http://services.TRNValidator.webservices.fsl.org", className = "fsl.ta.toms.roms.trnwebservice.GetFSLServiceResponse")
    public String getFSLService(
        @WebParam(name = "value", targetNamespace = "")
        String value)
        throws IncompleteTRNException_Exception, InvalidTRNException_Exception, InvalidTrnBranchException_Exception, NotValidTrnTypeException_Exception, RetiredTRNException_Exception, SystemErrorException_Exception
    ;

    /**
     * 
     * @param trnNbr
     * @return
     *     returns fsl.ta.toms.roms.trnwebservice.BusinessDetailsDTO
     * @throws NotValidTrnTypeException_Exception
     * @throws InvalidTRNException_Exception
     * @throws RetiredTRNException_Exception
     * @throws SystemErrorException_Exception
     * @throws InvalidTrnBranchException_Exception
     * @throws IncompleteTRNException_Exception
     */
    @WebMethod(action = "getBusinessDetails")
    @WebResult(name = "getBusinessDetailsReturn", targetNamespace = "")
    @RequestWrapper(localName = "getBusinessDetails", targetNamespace = "http://services.TRNValidator.webservices.fsl.org", className = "fsl.ta.toms.roms.trnwebservice.GetBusinessDetails")
    @ResponseWrapper(localName = "getBusinessDetailsResponse", targetNamespace = "http://services.TRNValidator.webservices.fsl.org", className = "fsl.ta.toms.roms.trnwebservice.GetBusinessDetailsResponse")
    public BusinessDetailsDTO getBusinessDetails(
        @WebParam(name = "trnNbr", targetNamespace = "")
        Integer trnNbr)
        throws IncompleteTRNException_Exception, InvalidTRNException_Exception, InvalidTrnBranchException_Exception, NotValidTrnTypeException_Exception, RetiredTRNException_Exception, SystemErrorException_Exception
    ;

    /**
     * 
     * @param trnNbr
     * @return
     *     returns fsl.ta.toms.roms.trnwebservice.IndividualDetailsDTO
     * @throws NotValidTrnTypeException_Exception
     * @throws InvalidTRNException_Exception
     * @throws SystemErrorException_Exception
     * @throws InvalidTrnBranchException_Exception
     * @throws IncompleteTRNException_Exception
     */
    @WebMethod(action = "getInvidualDetails")
    @WebResult(name = "getInvidualDetailsReturn", targetNamespace = "")
    @RequestWrapper(localName = "getInvidualDetails", targetNamespace = "http://services.TRNValidator.webservices.fsl.org", className = "fsl.ta.toms.roms.trnwebservice.GetInvidualDetails")
    @ResponseWrapper(localName = "getInvidualDetailsResponse", targetNamespace = "http://services.TRNValidator.webservices.fsl.org", className = "fsl.ta.toms.roms.trnwebservice.GetInvidualDetailsResponse")
    public IndividualDetailsDTO getInvidualDetails(
        @WebParam(name = "trnNbr", targetNamespace = "")
        Integer trnNbr)
        throws IncompleteTRNException_Exception, InvalidTRNException_Exception, InvalidTrnBranchException_Exception, NotValidTrnTypeException_Exception, SystemErrorException_Exception
    ;

    /**
     * 
     * @param trnNbr
     * @return
     *     returns fsl.ta.toms.roms.trnwebservice.IndividualDTO
     * @throws NotValidTrnTypeException_Exception
     * @throws RetiredTRNException_Exception
     * @throws InvalidTRNException_Exception
     * @throws SystemErrorException_Exception
     * @throws IncompleteTRNException_Exception
     */
    @WebMethod(action = "getIndividual")
    @WebResult(name = "getIndividualReturn", targetNamespace = "")
    @RequestWrapper(localName = "getIndividual", targetNamespace = "http://services.TRNValidator.webservices.fsl.org", className = "fsl.ta.toms.roms.trnwebservice.GetIndividual")
    @ResponseWrapper(localName = "getIndividualResponse", targetNamespace = "http://services.TRNValidator.webservices.fsl.org", className = "fsl.ta.toms.roms.trnwebservice.GetIndividualResponse")
    public IndividualDTO getIndividual(
        @WebParam(name = "trnNbr", targetNamespace = "")
        Integer trnNbr)
        throws IncompleteTRNException_Exception, InvalidTRNException_Exception, NotValidTrnTypeException_Exception, RetiredTRNException_Exception, SystemErrorException_Exception
    ;

    /**
     * 
     * @param trnNbr
     * @return
     *     returns fsl.ta.toms.roms.trnwebservice.IndividualExtendedDTO
     * @throws NotValidTrnTypeException_Exception
     * @throws RequiredInputMissingException_Exception
     * @throws InvalidTRNException_Exception
     * @throws InvalidInputException_Exception
     * @throws SystemErrorException_Exception
     */
    @WebMethod(action = "getIndividualExtended")
    @WebResult(name = "getIndividualExtendedReturn", targetNamespace = "")
    @RequestWrapper(localName = "getIndividualExtended", targetNamespace = "http://services.TRNValidator.webservices.fsl.org", className = "fsl.ta.toms.roms.trnwebservice.GetIndividualExtended")
    @ResponseWrapper(localName = "getIndividualExtendedResponse", targetNamespace = "http://services.TRNValidator.webservices.fsl.org", className = "fsl.ta.toms.roms.trnwebservice.GetIndividualExtendedResponse")
    public IndividualExtendedDTO getIndividualExtended(
        @WebParam(name = "trnNbr", targetNamespace = "")
        String trnNbr)
        throws InvalidInputException_Exception, InvalidTRNException_Exception, NotValidTrnTypeException_Exception, RequiredInputMissingException_Exception, SystemErrorException_Exception
    ;

    /**
     * 
     * @param branchNbr
     * @param trnNbr
     * @return
     *     returns fsl.ta.toms.roms.trnwebservice.TrnDTO
     * @throws NotValidTrnTypeException_Exception
     * @throws SystemErrorException_Exception
     * @throws InvalidTrnBranchException_Exception
     */
    @WebMethod(action = "validateTRN")
    @WebResult(name = "validateTRNReturn", targetNamespace = "")
    @RequestWrapper(localName = "validateTRN", targetNamespace = "http://services.TRNValidator.webservices.fsl.org", className = "fsl.ta.toms.roms.trnwebservice.ValidateTRN")
    @ResponseWrapper(localName = "validateTRNResponse", targetNamespace = "http://services.TRNValidator.webservices.fsl.org", className = "fsl.ta.toms.roms.trnwebservice.ValidateTRNResponse")
    public TrnDTO validateTRN(
        @WebParam(name = "trnNbr", targetNamespace = "")
        Integer trnNbr,
        @WebParam(name = "branchNbr", targetNamespace = "")
        Short branchNbr)
        throws InvalidTrnBranchException_Exception, NotValidTrnTypeException_Exception, SystemErrorException_Exception
    ;

    /**
     * 
     * @param branchNbr
     * @param trnNbr
     * @return
     *     returns fsl.ta.toms.roms.trnwebservice.TrnExtendedDTO
     * @throws NotValidTrnTypeException_Exception
     * @throws RetiredTRNException_Exception
     * @throws InvalidTRNException_Exception
     * @throws SystemErrorException_Exception
     * @throws InvalidTrnBranchException_Exception
     * @throws IncompleteTRNException_Exception
     */
    @WebMethod(action = "getTRNData")
    @WebResult(name = "getTRNDataReturn", targetNamespace = "")
    @RequestWrapper(localName = "getTRNData", targetNamespace = "http://services.TRNValidator.webservices.fsl.org", className = "fsl.ta.toms.roms.trnwebservice.GetTRNData")
    @ResponseWrapper(localName = "getTRNDataResponse", targetNamespace = "http://services.TRNValidator.webservices.fsl.org", className = "fsl.ta.toms.roms.trnwebservice.GetTRNDataResponse")
    public TrnExtendedDTO getTRNData(
        @WebParam(name = "trnNbr", targetNamespace = "")
        Integer trnNbr,
        @WebParam(name = "branchNbr", targetNamespace = "")
        Short branchNbr)
        throws IncompleteTRNException_Exception, InvalidTRNException_Exception, InvalidTrnBranchException_Exception, NotValidTrnTypeException_Exception, RetiredTRNException_Exception, SystemErrorException_Exception
    ;

    /**
     * 
     * @param branchNbr
     * @param trnNbr
     * @return
     *     returns fsl.ta.toms.roms.trnwebservice.TrnExtendedDTO
     * @throws InvalidTRNException_Exception
     */
    @WebMethod(action = "validateProvisionalTrn")
    @WebResult(name = "validateProvisionalTrnReturn", targetNamespace = "")
    @RequestWrapper(localName = "validateProvisionalTrn", targetNamespace = "http://services.TRNValidator.webservices.fsl.org", className = "fsl.ta.toms.roms.trnwebservice.ValidateProvisionalTrn")
    @ResponseWrapper(localName = "validateProvisionalTrnResponse", targetNamespace = "http://services.TRNValidator.webservices.fsl.org", className = "fsl.ta.toms.roms.trnwebservice.ValidateProvisionalTrnResponse")
    public TrnExtendedDTO validateProvisionalTrn(
        @WebParam(name = "trnNbr", targetNamespace = "")
        Integer trnNbr,
        @WebParam(name = "branchNbr", targetNamespace = "")
        Short branchNbr)
        throws InvalidTRNException_Exception
    ;

    /**
     * 
     * @param startPeriod
     * @param endPeriod
     * @return
     *     returns fsl.ta.toms.roms.trnwebservice.ArrayOf5444426031440052060NillableString
     * @throws SystemErrorException_Exception
     */
    @WebMethod(action = "updatedTRNList")
    @WebResult(name = "updatedTRNListReturn", targetNamespace = "")
    @RequestWrapper(localName = "updatedTRNList", targetNamespace = "http://services.TRNValidator.webservices.fsl.org", className = "fsl.ta.toms.roms.trnwebservice.UpdatedTRNList")
    @ResponseWrapper(localName = "updatedTRNListResponse", targetNamespace = "http://services.TRNValidator.webservices.fsl.org", className = "fsl.ta.toms.roms.trnwebservice.UpdatedTRNListResponse")
    public ArrayOf5444426031440052060NillableString updatedTRNList(
        @WebParam(name = "startPeriod", targetNamespace = "")
        XMLGregorianCalendar startPeriod,
        @WebParam(name = "endPeriod", targetNamespace = "")
        XMLGregorianCalendar endPeriod)
        throws SystemErrorException_Exception
    ;

}
