//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package fsl.ta.toms.roms.trnwebservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "TrnValidatorService", targetNamespace = "http://services.TRNValidator.webservices.fsl.org", wsdlLocation = "WEB-INF/wsdl/TrnValidator.wsdl")
public class TrnValidatorService
    extends Service
{

    private final static URL TRNVALIDATORSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRNVALIDATORSERVICE_EXCEPTION;
    private final static QName TRNVALIDATORSERVICE_QNAME = new QName("http://services.TRNValidator.webservices.fsl.org", "TrnValidatorService");

    static {
            TRNVALIDATORSERVICE_WSDL_LOCATION = fsl.ta.toms.roms.trnwebservice.TrnValidatorService.class.getResource("/WEB-INF/wsdl/TrnValidator.wsdl");
        WebServiceException e = null;
        if (TRNVALIDATORSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/TrnValidator.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        TRNVALIDATORSERVICE_EXCEPTION = e;
    }

    public TrnValidatorService() {
        super(__getWsdlLocation(), TRNVALIDATORSERVICE_QNAME);
    }

    public TrnValidatorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRNVALIDATORSERVICE_QNAME, features);
    }

    public TrnValidatorService(URL wsdlLocation) {
        super(wsdlLocation, TRNVALIDATORSERVICE_QNAME);
    }

    public TrnValidatorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRNVALIDATORSERVICE_QNAME, features);
    }

    public TrnValidatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TrnValidatorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TrnValidatorSEI
     */
    @WebEndpoint(name = "TrnValidator")
    public TrnValidatorSEI getTrnValidator() {
        return super.getPort(new QName("http://services.TRNValidator.webservices.fsl.org", "TrnValidator"), TrnValidatorSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TrnValidatorSEI
     */
    @WebEndpoint(name = "TrnValidator")
    public TrnValidatorSEI getTrnValidator(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.TRNValidator.webservices.fsl.org", "TrnValidator"), TrnValidatorSEI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRNVALIDATORSERVICE_EXCEPTION!= null) {
            throw TRNVALIDATORSERVICE_EXCEPTION;
        }
        return TRNVALIDATORSERVICE_WSDL_LOCATION;
    }

}
