//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package fsl.ta.toms.roms.webservices.trn;

import javax.xml.ws.WebFault;

import fsl.ta.toms.roms.trnwebservice.SystemErrorException;

@WebFault(name = "SystemErrorException", targetNamespace = "http://exceptions.common.webservices.fsl.org")
public class SystemErrorExceptionException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SystemErrorException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SystemErrorExceptionException(String message, SystemErrorException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public SystemErrorExceptionException(String message, SystemErrorException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: fsl.ta.toms.roms.webservices.trn.SystemErrorException
     */
    public SystemErrorException getFaultInfo() {
        return faultInfo;
    }

}
