//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package org.fsl.webservices.common.exceptions;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InvalidTrnBranchException complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvalidTrnBranchException">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="strException" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvalidTrnBranchException", propOrder = {
    "strException"
})
public class InvalidTrnBranchException
    implements Serializable
{

    @XmlElement(required = true, nillable = true)
    protected String strException;

    /**
     * Gets the value of the strException property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrException() {
        return strException;
    }

    /**
     * Sets the value of the strException property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrException(String value) {
        this.strException = value;
    }

}
