//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package fsl.ta.toms.roms.amvswebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "FslMotorVehicle", targetNamespace = "http://vehicle.ws.fsl.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FslMotorVehicle {


    /**
     * 
     * @param motorVehicleID
     * @param chassisNo
     * @param plateNo
     * @return
     *     returns fsl.ta.toms.roms.amvswebservice.VehInfo
     * @throws FslWebServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "getVehicleReturn", targetNamespace = "")
    @RequestWrapper(localName = "getVehicle", targetNamespace = "http://vehicle.ws.fsl.org", className = "fsl.ta.toms.roms.amvswebservice.GetVehicle")
    @ResponseWrapper(localName = "getVehicleResponse", targetNamespace = "http://vehicle.ws.fsl.org", className = "fsl.ta.toms.roms.amvswebservice.GetVehicleResponse")
    public VehInfo getVehicle(
        @WebParam(name = "plateNo", targetNamespace = "")
        String plateNo,
        @WebParam(name = "motorVehicleID", targetNamespace = "")
        String motorVehicleID,
        @WebParam(name = "chassisNo", targetNamespace = "")
        String chassisNo)
        throws FslWebServiceException_Exception
    ;

    /**
     * 
     * @param motorVehicleID
     * @param chassisNo
     * @param plateNo
     * @return
     *     returns fsl.ta.toms.roms.amvswebservice.Vehicle
     * @throws FslWebServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "getVehicleDetailsReturn", targetNamespace = "")
    @RequestWrapper(localName = "getVehicleDetails", targetNamespace = "http://vehicle.ws.fsl.org", className = "fsl.ta.toms.roms.amvswebservice.GetVehicleDetails")
    @ResponseWrapper(localName = "getVehicleDetailsResponse", targetNamespace = "http://vehicle.ws.fsl.org", className = "fsl.ta.toms.roms.amvswebservice.GetVehicleDetailsResponse")
    public Vehicle getVehicleDetails(
        @WebParam(name = "plateNo", targetNamespace = "")
        String plateNo,
        @WebParam(name = "motorVehicleID", targetNamespace = "")
        String motorVehicleID,
        @WebParam(name = "chassisNo", targetNamespace = "")
        String chassisNo)
        throws FslWebServiceException_Exception
    ;

}
