//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package fsl.ta.toms.roms.amvswebservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "FslMotorVehicleService", targetNamespace = "http://vehicle.ws.fsl.org", wsdlLocation = "WEB-INF/wsdl/FslMotorVehicle.wsdl")
public class FslMotorVehicleService
    extends Service
{

    private final static URL FSLMOTORVEHICLESERVICE_WSDL_LOCATION;
    private final static WebServiceException FSLMOTORVEHICLESERVICE_EXCEPTION;
    private final static QName FSLMOTORVEHICLESERVICE_QNAME = new QName("http://vehicle.ws.fsl.org", "FslMotorVehicleService");

    static {
            FSLMOTORVEHICLESERVICE_WSDL_LOCATION = fsl.ta.toms.roms.amvswebservice.FslMotorVehicleService.class.getResource("/WEB-INF/wsdl/FslMotorVehicle.wsdl");
        WebServiceException e = null;
        if (FSLMOTORVEHICLESERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/FslMotorVehicle.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        FSLMOTORVEHICLESERVICE_EXCEPTION = e;
    }

    public FslMotorVehicleService() {
        super(__getWsdlLocation(), FSLMOTORVEHICLESERVICE_QNAME);
    }

    public FslMotorVehicleService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FSLMOTORVEHICLESERVICE_QNAME, features);
    }

    public FslMotorVehicleService(URL wsdlLocation) {
        super(wsdlLocation, FSLMOTORVEHICLESERVICE_QNAME);
    }

    public FslMotorVehicleService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FSLMOTORVEHICLESERVICE_QNAME, features);
    }

    public FslMotorVehicleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FslMotorVehicleService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FslMotorVehicle
     */
    @WebEndpoint(name = "FslMotorVehicle")
    public FslMotorVehicle getFslMotorVehicle() {
        return super.getPort(new QName("http://vehicle.ws.fsl.org", "FslMotorVehicle"), FslMotorVehicle.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FslMotorVehicle
     */
    @WebEndpoint(name = "FslMotorVehicle")
    public FslMotorVehicle getFslMotorVehicle(WebServiceFeature... features) {
        return super.getPort(new QName("http://vehicle.ws.fsl.org", "FslMotorVehicle"), FslMotorVehicle.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FSLMOTORVEHICLESERVICE_EXCEPTION!= null) {
            throw FSLMOTORVEHICLESERVICE_EXCEPTION;
        }
        return FSLMOTORVEHICLESERVICE_WSDL_LOCATION;
    }

}
