//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package fsl.ta.toms.roms.amvswebservice;

import javax.xml.ws.WebFault;

@WebFault(name = "FslWebServiceException", targetNamespace = "http://exceptions.ws.fsl.org")
public class FslWebServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FslWebServiceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FslWebServiceException_Exception(String message, FslWebServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public FslWebServiceException_Exception(String message, FslWebServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: fsl.ta.toms.roms.amvswebservice.FslWebServiceException
     */
    public FslWebServiceException getFaultInfo() {
        return faultInfo;
    }

}
