//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package fsl.ta.toms.roms.amvswebservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fsl.ta.toms.roms.amvswebservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FslWebServiceException_QNAME = new QName("http://exceptions.ws.fsl.org", "FslWebServiceException");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fsl.ta.toms.roms.amvswebservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetVehicle }
     * 
     */
    public GetVehicle createGetVehicle() {
        return new GetVehicle();
    }

    /**
     * Create an instance of {@link GetVehicleResponse }
     * 
     */
    public GetVehicleResponse createGetVehicleResponse() {
        return new GetVehicleResponse();
    }

    /**
     * Create an instance of {@link VehInfo }
     * 
     */
    public VehInfo createVehInfo() {
        return new VehInfo();
    }

    /**
     * Create an instance of {@link GetVehicleDetails }
     * 
     */
    public GetVehicleDetails createGetVehicleDetails() {
        return new GetVehicleDetails();
    }

    /**
     * Create an instance of {@link GetVehicleDetailsResponse }
     * 
     */
    public GetVehicleDetailsResponse createGetVehicleDetailsResponse() {
        return new GetVehicleDetailsResponse();
    }

    /**
     * Create an instance of {@link Vehicle }
     * 
     */
    public Vehicle createVehicle() {
        return new Vehicle();
    }

    /**
     * Create an instance of {@link VehInsurance }
     * 
     */
    public VehInsurance createVehInsurance() {
        return new VehInsurance();
    }

    /**
     * Create an instance of {@link VehMvrc }
     * 
     */
    public VehMvrc createVehMvrc() {
        return new VehMvrc();
    }

    /**
     * Create an instance of {@link ArrayOfVehOwner }
     * 
     */
    public ArrayOfVehOwner createArrayOfVehOwner() {
        return new ArrayOfVehOwner();
    }

    /**
     * Create an instance of {@link VehOwner }
     * 
     */
    public VehOwner createVehOwner() {
        return new VehOwner();
    }

    /**
     * Create an instance of {@link ArrayOfVehLien }
     * 
     */
    public ArrayOfVehLien createArrayOfVehLien() {
        return new ArrayOfVehLien();
    }

    /**
     * Create an instance of {@link VehLien }
     * 
     */
    public VehLien createVehLien() {
        return new VehLien();
    }

    /**
     * Create an instance of {@link VehFitness }
     * 
     */
    public VehFitness createVehFitness() {
        return new VehFitness();
    }

    /**
     * Create an instance of {@link FslWebServiceException }
     * 
     */
    public FslWebServiceException createFslWebServiceException() {
        return new FslWebServiceException();
    }

    /**
     * Create an instance of {@link ArrayOf873062395NillableString }
     * 
     */
    public ArrayOf873062395NillableString createArrayOf873062395NillableString() {
        return new ArrayOf873062395NillableString();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FslWebServiceException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://exceptions.ws.fsl.org", name = "FslWebServiceException")
    public JAXBElement<FslWebServiceException> createFslWebServiceException(FslWebServiceException value) {
        return new JAXBElement<FslWebServiceException>(_FslWebServiceException_QNAME, FslWebServiceException.class, null, value);
    }

}
