//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package fsl.ta.toms.roms.amvswebservice;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VehInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VehInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="motorVehicleID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="plateRegistrationNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="chassisNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="engineNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vehicleStatusCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vehicleStatusDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="plateTypeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="plateTypeDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vehicleYear" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vehicleModel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vehicleColour" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vehicleTypeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vehicleTypeDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vehicleMakeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vehicleMakeDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vehicleBodyTypeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vehicleBodyTypeDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VehInfo", propOrder = {
    "motorVehicleID",
    "plateRegistrationNo",
    "chassisNo",
    "engineNo",
    "vehicleStatusCode",
    "vehicleStatusDesc",
    "plateTypeCode",
    "plateTypeDesc",
    "vehicleYear",
    "vehicleModel",
    "vehicleColour",
    "vehicleTypeCode",
    "vehicleTypeDesc",
    "vehicleMakeCode",
    "vehicleMakeDesc",
    "vehicleBodyTypeCode",
    "vehicleBodyTypeDesc"
})
public class VehInfo
    implements Serializable
{

    @XmlElement(required = true, nillable = true)
    protected String motorVehicleID;
    @XmlElement(required = true, nillable = true)
    protected String plateRegistrationNo;
    @XmlElement(required = true, nillable = true)
    protected String chassisNo;
    @XmlElement(required = true, nillable = true)
    protected String engineNo;
    @XmlElement(required = true, nillable = true)
    protected String vehicleStatusCode;
    @XmlElement(required = true, nillable = true)
    protected String vehicleStatusDesc;
    @XmlElement(required = true, nillable = true)
    protected String plateTypeCode;
    @XmlElement(required = true, nillable = true)
    protected String plateTypeDesc;
    @XmlElement(required = true, nillable = true)
    protected String vehicleYear;
    @XmlElement(required = true, nillable = true)
    protected String vehicleModel;
    @XmlElement(required = true, nillable = true)
    protected String vehicleColour;
    @XmlElement(required = true, nillable = true)
    protected String vehicleTypeCode;
    @XmlElement(required = true, nillable = true)
    protected String vehicleTypeDesc;
    @XmlElement(required = true, nillable = true)
    protected String vehicleMakeCode;
    @XmlElement(required = true, nillable = true)
    protected String vehicleMakeDesc;
    @XmlElement(required = true, nillable = true)
    protected String vehicleBodyTypeCode;
    @XmlElement(required = true, nillable = true)
    protected String vehicleBodyTypeDesc;

    /**
     * Gets the value of the motorVehicleID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotorVehicleID() {
        return motorVehicleID;
    }

    /**
     * Sets the value of the motorVehicleID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotorVehicleID(String value) {
        this.motorVehicleID = value;
    }

    /**
     * Gets the value of the plateRegistrationNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlateRegistrationNo() {
        return plateRegistrationNo;
    }

    /**
     * Sets the value of the plateRegistrationNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlateRegistrationNo(String value) {
        this.plateRegistrationNo = value;
    }

    /**
     * Gets the value of the chassisNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChassisNo() {
        return chassisNo;
    }

    /**
     * Sets the value of the chassisNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChassisNo(String value) {
        this.chassisNo = value;
    }

    /**
     * Gets the value of the engineNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngineNo() {
        return engineNo;
    }

    /**
     * Sets the value of the engineNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngineNo(String value) {
        this.engineNo = value;
    }

    /**
     * Gets the value of the vehicleStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleStatusCode() {
        return vehicleStatusCode;
    }

    /**
     * Sets the value of the vehicleStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleStatusCode(String value) {
        this.vehicleStatusCode = value;
    }

    /**
     * Gets the value of the vehicleStatusDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleStatusDesc() {
        return vehicleStatusDesc;
    }

    /**
     * Sets the value of the vehicleStatusDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleStatusDesc(String value) {
        this.vehicleStatusDesc = value;
    }

    /**
     * Gets the value of the plateTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlateTypeCode() {
        return plateTypeCode;
    }

    /**
     * Sets the value of the plateTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlateTypeCode(String value) {
        this.plateTypeCode = value;
    }

    /**
     * Gets the value of the plateTypeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlateTypeDesc() {
        return plateTypeDesc;
    }

    /**
     * Sets the value of the plateTypeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlateTypeDesc(String value) {
        this.plateTypeDesc = value;
    }

    /**
     * Gets the value of the vehicleYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleYear() {
        return vehicleYear;
    }

    /**
     * Sets the value of the vehicleYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleYear(String value) {
        this.vehicleYear = value;
    }

    /**
     * Gets the value of the vehicleModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleModel() {
        return vehicleModel;
    }

    /**
     * Sets the value of the vehicleModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleModel(String value) {
        this.vehicleModel = value;
    }

    /**
     * Gets the value of the vehicleColour property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleColour() {
        return vehicleColour;
    }

    /**
     * Sets the value of the vehicleColour property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleColour(String value) {
        this.vehicleColour = value;
    }

    /**
     * Gets the value of the vehicleTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleTypeCode() {
        return vehicleTypeCode;
    }

    /**
     * Sets the value of the vehicleTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleTypeCode(String value) {
        this.vehicleTypeCode = value;
    }

    /**
     * Gets the value of the vehicleTypeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleTypeDesc() {
        return vehicleTypeDesc;
    }

    /**
     * Sets the value of the vehicleTypeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleTypeDesc(String value) {
        this.vehicleTypeDesc = value;
    }

    /**
     * Gets the value of the vehicleMakeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleMakeCode() {
        return vehicleMakeCode;
    }

    /**
     * Sets the value of the vehicleMakeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleMakeCode(String value) {
        this.vehicleMakeCode = value;
    }

    /**
     * Gets the value of the vehicleMakeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleMakeDesc() {
        return vehicleMakeDesc;
    }

    /**
     * Sets the value of the vehicleMakeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleMakeDesc(String value) {
        this.vehicleMakeDesc = value;
    }

    /**
     * Gets the value of the vehicleBodyTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleBodyTypeCode() {
        return vehicleBodyTypeCode;
    }

    /**
     * Sets the value of the vehicleBodyTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleBodyTypeCode(String value) {
        this.vehicleBodyTypeCode = value;
    }

    /**
     * Gets the value of the vehicleBodyTypeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleBodyTypeDesc() {
        return vehicleBodyTypeDesc;
    }

    /**
     * Sets the value of the vehicleBodyTypeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleBodyTypeDesc(String value) {
        this.vehicleBodyTypeDesc = value;
    }

}
